### ISSUE TITLE
Different deflate result from pako

### ISSUE THREAD

**Issue by zwz** [drbh/wasm-flate#6]
Here is what I did:
```
var x = flate.deflate_encode_raw('test')
var y = pako.deflateRaw('test')
console.log(x, y)
```
The results are different.
Should they use the same algorithm?

**Comment by drbh** [comment]
@zwz great question.

The reason the output your are getting is different is because the input is being interpreted differently by both functions.

If you are more explicit about the input you'll see the results are equivalent. 

```js
var flate = require('wasm-flate');
var pako = require('pako');

var data = new Uint8Array( Buffer.from('Hello World') );
// Uint8Array [
//    72, 101, 108, 108,
//   111,  32,  87, 111,
//   114, 108, 100
// ]
```

compress with wasm-flate
```js
flate.deflate_encode_raw(data)
// Uint8Array [
//   243, 72, 205, 201, 201,
//    87,  8, 207,  47, 202,
//    73,  1,   0
// ]
```


Then compress with pako
```js
pako.deflateRaw(data)
// Uint8Array [
//   243, 72, 205, 201, 201,
//    87,  8, 207,  47, 202,
//    73,  1,   0
// ]
```
 
you can see the output is the same 🎉

you can even compress with one library and decompress with the other one

```js
var data = new Uint8Array( Buffer.from('Hello World') );
var compressed_with_wasm_flate = flate.deflate_encode_raw(data)
var decompressed_with_pako = pako.inflateRaw(compressed_with_wasm_flate)

// covert to a string - since JS doesnt let us directly compare UintArrays
var original = new TextDecoder("utf-8").decode(data)
var evaluated = new TextDecoder("utf-8").decode(decompressed_with_pako)
original === evaluated
// true
```

**Comment by zwz** [comment]
Oh, I see, I have to convert string to Uint8Array first. Thanks.

**Comment by XxSven** [comment]
the word Raw is misleading between the two libraries:
With pako it means [no wrapper](https://nodeca.github.io/pako/#inflateRaw), whereas with wasm-flate it means Uint8Array as parameter instead of string
